# Generated by Django 2.0.2 on 2018-06-17 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(help_text='Property Address', max_length=200)),
                ('price', models.IntegerField(blank=True, default=0, help_text='Accepted Price')),
                ('physical_cr', models.CharField(blank=True, default='', max_length=200)),
                ('appraisal_cr', models.CharField(blank=True, default='', max_length=200)),
                ('loan_cr', models.CharField(blank=True, default='', max_length=200)),
                ('coe', models.CharField(blank=True, default='', max_length=200)),
                ('seller_name', models.CharField(blank=True, default='', max_length=200)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=200)),
                ('listing_broker_name', models.CharField(blank=True, default='', max_length=200)),
                ('escrow', models.IntegerField(blank=True, default=0)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('lender', models.CharField(blank=True, default='', max_length=200)),
                ('hoa_name', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='current_task',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='listing.Task'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vendors',
            field=models.ManyToManyField(blank=True, default='', to='listing.Vendor'),
        ),
    ]
